accounts/urls.py
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [

    url(r'^signup/$', views.signup_view, name="signup"),
    url(r'^login/$', views.login_view, name="login"),
    url(r'^logout/$', views.logout_view, name="logout"),
    url(r'^profile/$', views.profile, name="profile"),
    url(r'^profile/edit/$', views.edit_profile, name="edit_profile"),
    url(r'^passwordchange/$', views.passwordchange_view, name="passwordchange"),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',views.activate_view, name="activate"),
]

djangonautic/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from articles import views as article_view



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^search/', include(('search.urls'), namespace='search')),
    url(r'^articles/', include('articles.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^about/$', views.about, name="about"),
    url(r'^$', views.homepage, name="home"),
]


if settings.DEBUG:
    urlpatterns= urlpatterns + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)
    urlpatterns= urlpatterns + static(settings.STATIC_URL, document_root= settings.STATIC_ROOT)



if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns= urlpatterns + static(settings.STATIC_URL, document_root= settings.STATIC_ROOT)

search/urls.py
from django.conf.urls import url
from django.contrib import admin
from .views import (searcharticles)
from . import views

app_name='search'


urlpatterns = [
    url('^$', views.searcharticles, name='searcharticles')
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')
    birth_date = models.DateField(null=True, blank=True)

    def __str__(self):
        return f'{self.user.username} Profile'


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
            Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from .models import Profile



class SignupForm(UserCreationForm):
    email = forms.EmailField(max_length=200, help_text='Required')
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')

        def save(self, commit=True):
            user = super(SignupForm, self).save(commit=False)
            user.first_name = cleaned_data['first_name']
            user.last_name = cleaned_data['last_name']
            user.email = cleaned_data['email']

            if commit:
                user.save()

                return user

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('bio','birth_date')


class editprofileform(UserChangeForm):
    class Meta:
        model = User
        fields = {
        'email',
        'first_name',
        'last_name',
        }

accounts/views.py
from django.shortcuts import render, redirect, HttpResponseRedirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm, UserChangeForm
from django.contrib.auth import login, logout, update_session_auth_hash, authenticate
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from .forms import SignupForm, UserForm, ProfileForm, editprofileform
from .token import account_activation_token
from django.contrib.auth.models import User
from django.core.mail import EmailMessage
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from . models import Profile
from django.forms.models import inlineformset_factory
from django.core.exceptions import PermissionDenied
from django.views.generic.base import TemplateView




def signup_view(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            current_site = get_current_site(request)
            mail_subject = 'Activate your blog account.'
            message = render_to_string('accounts/activation.html', {
                'user': user,
                'domain': current_site.domain,
                'uid':urlsafe_base64_encode(force_bytes(user.pk)),
                'token':account_activation_token.make_token(user),
            })
            to_email = form.cleaned_data.get('email')
            email = EmailMessage(
                        mail_subject, message, to=[to_email]
            )
            email.send()
            return HttpResponse('Please confirm your email address to complete the registration')
    else:
        form = SignupForm()
    return render(request, 'accounts/signup.html', {'form': form})

def activate_view(request, uidb64, token):
        try:
            uid = force_text(urlsafe_base64_decode(uidb64))
            user = User.objects.get(id=uid)
        except(TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None
        if user is not None and account_activation_token.check_token(user, token):
            user.is_active = True
            user.save()
            return HttpResponse('Thank you for your email confirmation. Now you can login your account.')
        else:
            return HttpResponse('Activation link is invalid!')

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('articles:list')

    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', { 'form': form })

def logout_view(request):
    if request.method == 'POST':
            logout(request)
            return redirect('templates/homepage.html')

def passwordchange_view(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'Your password was successfully updated!')
            return redirect('passwordchange')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'accounts/passwordchange.html', {'form': form })
@login_required
def edit_user(request,pk):
    user = User.objects.get(pk=pk)
    user_form = UserProfileForm(instance=user)

    ProfileInlineFormset = inlineformset_factory(User, UserProfile, fields=('user', 'bio'))
    formset = ProfileInlineFormset(instance=user)

    if request.user.is_authenticated() and request.user.id == user.id:
        if request.method == "POST":
            user_form = UserProfileForm(request.POST, request.FILES, instance=user)
            formset = ProfileInlineFormset(request.POST, request.FILES, instance=user)

            if user_form.is_valid():
                created_user = user_form.save(commit=False)
                formset = ProfileInlineFormset(request.POST, request.FILES, instance=created_user)

                if formset.is_valid():
                    created_user.save()
                    formset.save()
                    return HttpResponseRedirect('/accounts/profile/')

        return render(request, "account/account_update.html", {
            "noodle": pk,
            "noodle_form": user_form,
            "formset": formset,
        })
    else:
        raise PermissionDenied


def profile(request):
    args = {'user': request.user }
    return render(request, 'accounts/profile.html', args)


def edit_profile(request):
    if request.method == 'POST':
        form = editprofileform(request.POST, instance=request.user)

        if form.is_valid():
            form.save()
            return redirect('/accounts/profile/')
    else:
        form = editprofileform(instance=request.user)
        return render(request, 'accounts/edit_profile.html', {'form':form})

accounts/templates/accounts/Profile.html
{% extends 'base_layout.html' %}
{% load crispy_forms_tags %}

{% block content %}

  <form method="post">
      {% csrf_token %}
      {{ user_form.as_p }}
      {{ profile_form.as_p }}
    <button type="submit">Save changes</button>
  </form>
{% endblock %}

accounts/templates/accounts/activation.html
{% autoescape off %}
Hi ,
Please click on the link to confirm your registration,
http://{{ domain }}{% url 'accounts:activate' uidb64=uid token=token %}
{% endautoescape %}

accounts/templates/accounts/edit_profile.html
{% extends "base_layout.html" %}

{% block content %}


<div class="container">
  <nav>
    <a href="{% url 'accounts:passwordchange'%}">Change Password</a>
  </nav>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Confirm</button>
  </form>
  </div>



{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>Log in</h1>
    <form class="site-form" action="{% url 'accounts:login' %}" method="post">
        {% csrf_token %}
        {{ form }}
        {% if request.GET.next %}
          <input type="hidden" name="next" value="{{ request.GET.next }}">
        {% endif %}
        <input type="submit" value="Login">
      </form>
    <p>Not got an account? <a href="{% url 'accounts:signup' %}">Sign Up</a></p>
{% endblock %}

accounts/templates/accounts/passwordchange.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>Password Change</h1>
    <form class="site-form" action="{% url 'accounts:passwordchange' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <button type="submit">Save changes</button>
    </form>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base_layout.html' %}

{% block content %}
<body>
        <header>
          <h1>Profile</h1>
          <h2 class="flow=text">Welcome to your station traveler</h2>
          <ul>
            <li><a href="{% url 'accounts:edit_profile' %}">Edit Profile</a></li>
            <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
        </ul>

        </header>

        <form action="." method="POST"  class="padding">
          {% csrf_token %} {{ noodle_form.as_p }}
          <div class="divider"></div>
            {{ formset.managment_form }}
            {{ formset.as_p }}
            <div class="profilepicture>
                <img src="{{ user.profile.image.url }}" width="240" align="center" >
            </div>
            <main>

            <ul>
              <li>Username: {{ user }}</li>
              <li>first_name: {{ user.first_name }}</li>
              <li>last_name: {{ user.last_name }}</li>
              <li>email: {{ user.email }}</li>
              <li>Bio: {{ user.profile.bio }}</li>
              <li>birth date: {{ user.profile.birth_date }}</li>
            </ul>
            </main>
        </form>
</body>

{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="signup">

  <h2>Sign up</h2>
    <form class="signupform" method="post">
      {% csrf_token %}
      {% for field in form %}
        <p>
          {{ field.label_tag }}<br>
          {{ field }}
          {% if field.help_text %}
            <small style="display: none">{{ field.help_text }}</small>
          {% endif %}
          {% for error in field.errors %}
            <p style="color: red">{{ error }}</p>
          {% endfor %}
        </<p>
      {% endfor %}    <button type="submit">Sign up</button>
    </form>

  </div>
{% endblock %}

accounts/templates/accounts/userprofile.html
{% extends 'base_layout.html' %}

{% block content %}

<div class="col s12 m8 offset-m2">
    <div class="card">
      <div class="card-content">
      <h2 class="flow=text"> Update your information</h2>
        <form action="." method="POST"  class="padding">
          {% csrf_token %} {{ noodle_form.as_p }}
          <div class="divider"></div>
          {{ formset.managment_form }}
            {{ formset.as_p }}
            <button type="submit" class="btn-floating btn-large waves-light waves-effect"><i class="large material-icons">done</i></button>
            <a href="#" onclick="window.history.back(); return false;" title="Cancel" class="btn-floating waves-effect waves-light red"><i class="material-icons">history</i></a>

        </form>

      </div>

    </div>

</div>

{% endblock %}