accounts/urls.py
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [

    url(r'^signup/$', views.signup_view, name="signup"),
    url(r'^login/$', views.login_view, name="login"),
    url(r'^logout/$', views.logout_view, name="logout"),
    url(r'^profile/$', views.profile, name="profile"),
    url(r'^profile/edit/$', views.edit_profile, name="edit_profile"),
    url(r'^passwordchange/$', views.passwordchange_view, name="passwordchange"),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',views.activate_view, name="activate"),
]

articles/urls.py
from django.conf.urls import url
from . import views

app_name = 'articles'

urlpatterns = [
    url(r'^$', views.article_list, name="list"),
    url(r'^create/$', views.article_create, name="create"),
    url(r'^(?P<slug>[\w-]+)/$', views.article_detail, name="detail"),
]

djangonautic/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from articles import views as article_view



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^search/', include(('search.urls'), namespace='search')),
    url(r'^articles/', include('articles.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^about/$', views.about, name="about"),
    url(r'^$', views.homepage, name="home"),
]


if settings.DEBUG:
    urlpatterns= urlpatterns + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)
    urlpatterns= urlpatterns + static(settings.STATIC_URL, document_root= settings.STATIC_ROOT)



if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns= urlpatterns + static(settings.STATIC_URL, document_root= settings.STATIC_ROOT)

search/urls.py
from django.conf.urls import url
from django.contrib import admin
from .views import (searcharticles)
from . import views

app_name='search'


urlpatterns = [
    url('^$', views.searcharticles, name='searcharticles')
]

templates/about.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>About</title>
        <link rel="stylesheet" href="{% static 'styles.css' %}">
        <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Ubuntu:regular,bold&subset=Latin">
    </head>
    <body>
      <div class="about">
        <h1>About</h1>
        <p>Hi. We are two guys from a less known city of a dystopian country, while we're not lost and consumed by the sheer pressure of human survival,
        we smoke and create stuff, in the hope of finding the long lost peace that we all crave along the way. </p>

        </div>
    </body>
</html>

templates/base_layout.html
{% load static %}
{% load humanize %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Djangonauts</title>
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'styles.css' %}">
        <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css2?family=Raleway:ital,wght@1,500&display=swap">
        <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Ubuntu:regular,bold&subset=Latin">
        <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css2?family=Alata&display=swap">
    </head>
    <body>


        <div class="wrapper">
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>

templates/homepage.html
{% extends 'base_layout.html' %}
{% load static %}

{% block content%}

<body>
  <header>
    <div class="topnav">
          <a href="/about/" class="about">About</a>
            {% if user.is_authenticated %}

                <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                  {% csrf_token %}
                  <button type="submit">Logout</button>
                </form>

               <a href="{% url 'articles:create' %}" class="highlight">New Article</a>
               <a href="{% url 'accounts:profile' %}">Profile</a>
            {% else %}
               <a href="{% url 'accounts:login' %}" class="loginbutton">Login</a>
               <a href="{% url 'accounts:signup' %}" class="signupbutton">Signup</a>

            {% endif %}
            <div class="search-container">
              <form action="{% url 'search:searcharticles' %}" method="GET" value="{{request.GET.q}}">
              <input type="text" class="searchfeild" name="q" value="{{request.GET.q}}" placeholder="Search Playlists"/>
              <button type="submit" name="button" value="Search"><i class="material-icons">search</i></button>
              </form>


              {% if submitbutton == 'Search' and request.GET.q != '' %}
              {% if results %}
              <h1>Results for <b>{{ request.GET.q }}</b></h1>
              <br/><br/>

              {% for result in results %}

              {{result.title}}
              <br/>

              {{result.content}}
              <br/>

              {% endfor %}
              {% else %}
              its not the end of world
              {% endif %}
              {% endif %}
            </div>
    </div>
  </header>

      <div class="welcome">
        <h1>Welcome to <a class="nova" href="{% url 'home'%}">NOVA</a></h1>
        <p class="articlelist"> <a href="{% url 'articles:list' %}">Playlists</a></p>

      </div>
    </body>
{% endblock %}